CREATE TABLE tb_customers
(
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    email       VARCHAR(45),
    address     VARCHAR(255),
    CONSTRAINT pk_tb_customers PRIMARY KEY (customer_id)
);

CREATE TABLE tb_order
(
    order_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    local_date_time TIMESTAMP,
    customer_id     BIGINT,
    CONSTRAINT pk_tb_order PRIMARY KEY (order_id)
);

CREATE TABLE tb_order_items
(
    order_item_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_order_id     BIGINT,
    product_product_id INT,
    quantity           INT                                     NOT NULL,
    CONSTRAINT pk_tb_orderitems PRIMARY KEY (order_item_id)
);

CREATE TABLE tb_products
(
    product_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    quantity   INT,
    version    INT,
    CONSTRAINT pk_tb_products PRIMARY KEY (product_id)
);

ALTER TABLE tb_customers
    ADD CONSTRAINT uc_tb_customers_email UNIQUE (email);

ALTER TABLE tb_order_items
    ADD CONSTRAINT FK_TB_ORDERITEMS_ON_ORDER_ORDER FOREIGN KEY (order_order_id) REFERENCES tb_order (order_id);

ALTER TABLE tb_order_items
    ADD CONSTRAINT FK_TB_ORDERITEMS_ON_PRODUCT_PRODUCT FOREIGN KEY (product_product_id) REFERENCES tb_products (product_id);

ALTER TABLE tb_order
    ADD CONSTRAINT FK_TB_ORDER_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES tb_customers (customer_id);