create TABLE tb_products
(
    product_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    quantity   INT,
    version    INT,
    CONSTRAINT pk_tb_products PRIMARY KEY (product_id)
);